import { initCalendar } from "./modules/calendar.js";
import { initModal } from "./modules/modal.js";
import { initPomodoro } from "./modules/pomodoro.js";
import { initToast } from "./modules/toast.js";
import { initTodo } from "./modules/todo.js";
import { initSectionToggle } from "./modules/sectionToggle.js";
import { initTheme } from "./modules/theme.js";
import { initKeyboardShortcuts } from "./modules/keyboard.js";
import { initStats } from "./modules/stats.js";
import { initFocusMode } from "./modules/focusMode.js";
import { initAchievements } from "./modules/achievements.js";
import { initModernTimer } from "./modules/modernTimer.js";
import { initSceneAndNav } from "./modules/sceneAndNav.js";
import { initI18n } from "./modules/i18n.js";
import { initVault } from "./modules/vault.js";
import { initKanban } from "./modules/kanban.js";
import { initHabits } from "./modules/habits.js";
import { initMood } from "./modules/mood.js";
import { initHero } from "./modules/gamification/hero.js";
import { initHeroUI } from "./modules/gamification/heroUI.js";
import { initCompanion } from "./modules/mascot/companion.js";
import { initPets } from "./modules/gamification/pets.js";
import { initExploration } from "./modules/gamification/tacticsExploration.js";
import { initTacticsUI } from "./modules/gamification/tacticsUI.js";
import { initHeroBanner } from "./modules/heroBanner.js";
import { initSampleData } from "./modules/sampleData.js";

document.addEventListener("DOMContentLoaded", () => {
  initI18n();
  initSampleData();
  initHeroBanner();
  initTheme();
  initStats();
  initCalendar();
  initModal();
  initToast();
  initPomodoro();
  initTodo();
  initMood();
  initHabits();
  initSectionToggle();
  initKeyboardShortcuts();
  initFocusMode();
  initAchievements();
  initModernTimer();
  initSceneAndNav();
  initVault();
  initKanban();
  initHero();
  initHeroUI();
  initPets();
  initExploration();
  initTacticsUI();
  initCompanion();
});
