/**
 * catalog.js — Gamification Items, Mounts & Equipment Catalog
 * High quality stats, rarities, costs, and sprite keys.
 */

"use strict";

export const ITEM_CATEGORIES = [
  { id: "weapon", label: "Weapons" },
  { id: "armor", label: "Armor" },
  { id: "headgear", label: "Helmets" },
  { id: "cloak", label: "Cloaks" },
  { id: "offhand", label: "Off-Hand" },
  { id: "mount", label: "Mounts" },
  { id: "consumable", label: "Potions" },
];

export const CATALOG = [
  // ─── Weapons ────────────────────────────────────────────────
  {
    id: "w_novice_dagger",
    name: "Novice Dagger",
    category: "weapon",
    rarity: "common",
    cost: 0,
    perk: "Basic starter blade",
    xpBonus: 0,
    goldBonus: 0,
    hpBonus: 0,
    lore: "Forged from dull practice iron. A humble weapon for an aspiring Chrono-Knight.",
    spriteKey: "dagger",
  },
  {
    id: "w_iron_sword",
    name: "Iron Broadsword",
    category: "weapon",
    rarity: "common",
    cost: 50,
    perk: "+5% Task XP",
    xpBonus: 0.05,
    goldBonus: 0,
    hpBonus: 0,
    lore: "Sturdy and balanced. Slices through hesitation with ease.",
    spriteKey: "broadsword",
  },
  {
    id: "w_blade_clarity",
    name: "Blade of Clarity",
    category: "weapon",
    rarity: "rare",
    cost: 120,
    perk: "+10% Task Gold",
    xpBonus: 0,
    goldBonus: 0.1,
    hpBonus: 0,
    lore: "Its mirror-polished edge dispels mental distractions on contact.",
    spriteKey: "clarity_blade",
  },
  {
    id: "w_staff_aeons",
    name: "Staff of Aeons",
    category: "weapon",
    rarity: "rare",
    cost: 250,
    perk: "+15% Pomodoro XP",
    xpBonus: 0.15,
    goldBonus: 0,
    hpBonus: 0,
    lore: "Humming with temporal magic, this staff slows the perceived passage of time.",
    spriteKey: "aeon_staff",
  },
  {
    id: "w_dual_daggers",
    name: "Twin Shadow Daggers",
    category: "weapon",
    rarity: "epic",
    cost: 400,
    perk: "+20% Subtask Gold",
    xpBonus: 0,
    goldBonus: 0.2,
    hpBonus: 0,
    lore: "Swift as thought. Designed to carve through checklists in rapid succession.",
    spriteKey: "twin_daggers",
  },
  {
    id: "w_sun_halberd",
    name: "Sun-Forged Halberd",
    category: "weapon",
    rarity: "epic",
    cost: 650,
    perk: "+25% All XP",
    xpBonus: 0.25,
    goldBonus: 0,
    hpBonus: 0,
    lore: "Blessed by the solar dawn. Radiates warm confidence through long work sessions.",
    spriteKey: "sun_halberd",
  },
  {
    id: "w_voidcleaver",
    name: "Voidcleaver of Chronos",
    category: "weapon",
    rarity: "legendary",
    cost: 1200,
    perk: "+35% All Rewards & +30 Boss DMG",
    xpBonus: 0.35,
    goldBonus: 0.35,
    hpBonus: 20,
    lore: "A legendary cosmic blade that severs the fabric of procrastination itself.",
    spriteKey: "voidcleaver",
  },

  // ─── Armor ──────────────────────────────────────────────────
  {
    id: "a_apprentice_tunic",
    name: "Apprentice Tunic",
    category: "armor",
    rarity: "common",
    cost: 0,
    perk: "Simple cloth garment",
    xpBonus: 0,
    goldBonus: 0,
    hpBonus: 0,
    lore: "Comfortable tunic woven from natural linen.",
    spriteKey: "tunic",
  },
  {
    id: "a_padded_leather",
    name: "Padded Leather Jerkin",
    category: "armor",
    rarity: "common",
    cost: 40,
    perk: "+10 Max Resolve (HP)",
    xpBonus: 0,
    goldBonus: 0,
    hpBonus: 10,
    lore: "Tanned hide lined with wool. Protects against unexpected fatigue.",
    spriteKey: "leather_armor",
  },
  {
    id: "a_mithril_plate",
    name: "Mithril Breastplate",
    category: "armor",
    rarity: "rare",
    cost: 160,
    perk: "+25 Max Resolve (HP)",
    xpBonus: 0,
    goldBonus: 0,
    hpBonus: 25,
    lore: "Light as a feather, hard as dragon scales. Built for marathon focus.",
    spriteKey: "mithril_plate",
  },
  {
    id: "a_chrono_vestments",
    name: "Chrono-Weave Vestments",
    category: "armor",
    rarity: "epic",
    cost: 350,
    perk: "+50 Max HP & +10% Focus XP",
    xpBonus: 0.1,
    goldBonus: 0,
    hpBonus: 50,
    lore: "Woven with strands of pure chronomantic silk. Shimmers with azure light.",
    spriteKey: "chrono_robe",
  },
  {
    id: "a_dragonscale",
    name: "Dragonscale Cuirass",
    category: "armor",
    rarity: "legendary",
    cost: 800,
    perk: "+100 Max HP & +15% All Rewards",
    xpBonus: 0.15,
    goldBonus: 0.15,
    hpBonus: 100,
    lore: "Crafted from the molted scales of the ancient Sloth Drake after its defeat.",
    spriteKey: "dragonscale_plate",
  },

  // ─── Helmets / Headgear ─────────────────────────────────────
  {
    id: "h_focus_band",
    name: "Focus Headband",
    category: "headgear",
    rarity: "common",
    cost: 0,
    perk: "Simple brow wrap",
    xpBonus: 0,
    goldBonus: 0,
    hpBonus: 0,
    lore: "Keeps sweat and wandering stray thoughts out of your eyes.",
    spriteKey: "headband",
  },
  {
    id: "h_scholar_circlet",
    name: "Scholar Circlet",
    category: "headgear",
    rarity: "rare",
    cost: 75,
    perk: "+8% XP on tasks",
    xpBonus: 0.08,
    goldBonus: 0,
    hpBonus: 0,
    lore: "A slim silver band with an amber gem that sharpens intellectual acuity.",
    spriteKey: "scholar_circlet",
  },
  {
    id: "h_knight_helm",
    name: "Knight's Greathelm",
    category: "headgear",
    rarity: "rare",
    cost: 180,
    perk: "+15 Max HP",
    xpBonus: 0,
    goldBonus: 0,
    hpBonus: 15,
    lore: "Heavy visor that blocks peripheral distractions completely.",
    spriteKey: "knight_helm",
  },
  {
    id: "h_chrono_goggles",
    name: "Chrono-Goggles",
    category: "headgear",
    rarity: "epic",
    cost: 320,
    perk: "+15% Gold & Time Perception",
    xpBonus: 0,
    goldBonus: 0.15,
    hpBonus: 10,
    lore: "Brass clockwork lenses that reveal hidden productive momentum.",
    spriteKey: "chrono_goggles",
  },
  {
    id: "h_epoch_crown",
    name: "Crown of the Epoch",
    category: "headgear",
    rarity: "legendary",
    cost: 850,
    perk: "+20% All Rewards & Radiant Aura",
    xpBonus: 0.2,
    goldBonus: 0.2,
    hpBonus: 40,
    lore: "Worn by the legendary Time Archons who mastered every second of life.",
    spriteKey: "epoch_crown",
  },

  // ─── Cloaks ─────────────────────────────────────────────────
  {
    id: "c_none",
    name: "No Cloak",
    category: "cloak",
    rarity: "common",
    cost: 0,
    perk: "Standard back",
    xpBonus: 0,
    goldBonus: 0,
    hpBonus: 0,
    lore: "Traveling without an outer mantle.",
    spriteKey: "none",
  },
  {
    id: "c_traveler_cloak",
    name: "Traveler's Cloak",
    category: "cloak",
    rarity: "common",
    cost: 45,
    perk: "+5 Max HP",
    xpBonus: 0,
    goldBonus: 0,
    hpBonus: 5,
    lore: "A weathered forest green cloak that repels rain and chilly drafts.",
    spriteKey: "traveler_cloak",
  },
  {
    id: "c_midnight_mantle",
    name: "Midnight Mantle",
    category: "cloak",
    rarity: "rare",
    cost: 150,
    perk: "+10% Task Gold",
    xpBonus: 0,
    goldBonus: 0.1,
    hpBonus: 10,
    lore: "Dark as the midnight sky; favored by nocturnal deep workers.",
    spriteKey: "midnight_cloak",
  },
  {
    id: "c_starweaver_cape",
    name: "Starweaver Cape",
    category: "cloak",
    rarity: "epic",
    cost: 380,
    perk: "+15% Focus XP",
    xpBonus: 0.15,
    goldBonus: 0,
    hpBonus: 20,
    lore: "Woven from stardust, leaving sparkling trails of inspiration behind you.",
    spriteKey: "starweaver_cape",
  },
  {
    id: "c_wings_diligence",
    name: "Wings of Diligence",
    category: "cloak",
    rarity: "legendary",
    cost: 950,
    perk: "+20% All Rewards & Flight",
    xpBonus: 0.2,
    goldBonus: 0.2,
    hpBonus: 50,
    lore: "Luminous angelic wings that carry the bearer effortlessly above procrastination.",
    spriteKey: "wings_diligence",
  },

  // ─── Off-Hand / Shields ─────────────────────────────────────
  {
    id: "o_none",
    name: "Empty Off-Hand",
    category: "offhand",
    rarity: "common",
    cost: 0,
    perk: "Free hand",
    xpBonus: 0,
    goldBonus: 0,
    hpBonus: 0,
    lore: "Ready to grab or carry tools.",
    spriteKey: "none",
  },
  {
    id: "o_wooden_buckler",
    name: "Oak Buckler",
    category: "offhand",
    rarity: "common",
    cost: 35,
    perk: "+5 Max HP",
    xpBonus: 0,
    goldBonus: 0,
    hpBonus: 5,
    lore: "Simple wooden shield bound with iron bands.",
    spriteKey: "buckler",
  },
  {
    id: "o_aegis_will",
    name: "Aegis of Will",
    category: "offhand",
    rarity: "rare",
    cost: 140,
    perk: "+20 Max HP",
    xpBonus: 0,
    goldBonus: 0,
    hpBonus: 20,
    lore: "Deflects incoming fatigue and keeps willpower steady under pressure.",
    spriteKey: "aegis_shield",
  },
  {
    id: "o_tome_epics",
    name: "Tome of Epics",
    category: "offhand",
    rarity: "epic",
    cost: 340,
    perk: "+15% Task XP",
    xpBonus: 0.15,
    goldBonus: 0,
    hpBonus: 10,
    lore: "A leather-bound spellbook chronicling triumphs over impossible deadlines.",
    spriteKey: "spell_tome",
  },
  {
    id: "o_chrono_orb",
    name: "Chrono-Hourglass Orb",
    category: "offhand",
    rarity: "legendary",
    cost: 750,
    perk: "+25% Pomodoro XP & +30 Max HP",
    xpBonus: 0.25,
    goldBonus: 0.1,
    hpBonus: 30,
    lore: "An ornate floating orb containing the sands of infinite focus.",
    spriteKey: "chrono_orb",
  },

  // ─── Mounts ─────────────────────────────────────────────────
  {
    id: "m_none",
    name: "On Foot",
    category: "mount",
    rarity: "common",
    cost: 0,
    perk: "Walking grounded",
    xpBonus: 0,
    goldBonus: 0,
    hpBonus: 0,
    lore: "Journeying across the realm on your own two feet.",
    spriteKey: "none",
  },
  {
    id: "m_solar_hare",
    name: "Solar Hare",
    category: "mount",
    rarity: "common",
    cost: 80,
    perk: "+5% Habit Streak XP",
    xpBonus: 0.05,
    goldBonus: 0,
    hpBonus: 0,
    lore: "A swift, glowing companion that hops enthusiastically alongside your daily routines.",
    spriteKey: "solar_hare",
  },
  {
    id: "m_battle_wolf",
    name: "Ironfang Battle Wolf",
    category: "mount",
    rarity: "rare",
    cost: 250,
    perk: "+12% Task Gold",
    xpBonus: 0,
    goldBonus: 0.12,
    hpBonus: 15,
    lore: "A loyal grey beast with amber eyes, bred to hunt down neglected backlog tasks.",
    spriteKey: "battle_wolf",
  },
  {
    id: "m_clockwork_steed",
    name: "Bronze Clockwork Steed",
    category: "mount",
    rarity: "epic",
    cost: 550,
    perk: "+15% Pomodoro XP & +20 Max HP",
    xpBonus: 0.15,
    goldBonus: 0.05,
    hpBonus: 20,
    lore: "A mechanical masterpiece engineered by Chrono-Guild artisans. Never tires.",
    spriteKey: "clockwork_steed",
  },
  {
    id: "m_cyber_drake",
    name: "Emerald Cyber Drake",
    category: "mount",
    rarity: "epic",
    cost: 950,
    perk: "+20% Boss Damage & +15% Gold",
    xpBonus: 0.1,
    goldBonus: 0.15,
    hpBonus: 40,
    lore: "A winged serpentine dragon adorned with jade neon circuit lines.",
    spriteKey: "cyber_drake",
  },
  {
    id: "m_celestial_griffin",
    name: "Celestial Griffin",
    category: "mount",
    rarity: "legendary",
    cost: 1500,
    perk: "+30% All Rewards & Sovereign Presence",
    xpBonus: 0.3,
    goldBonus: 0.3,
    hpBonus: 75,
    lore: "The pinnacle of airborne majesty. Feathers forged from starlight and pure resolve.",
    spriteKey: "celestial_griffin",
  },

  // ─── Consumables & Potions ──────────────────────────────────
  {
    id: "p_willpower_elixir",
    name: "Elixir of Willpower",
    category: "consumable",
    rarity: "common",
    cost: 25,
    perk: "Instantly restores 50 HP",
    xpBonus: 0,
    goldBonus: 0,
    hpBonus: 0,
    lore: "A refreshing brew of mint, citrus, and spring water that restores mental energy.",
    spriteKey: "potion_red",
  },
  {
    id: "p_focus_potion",
    name: "Potion of Swift Focus",
    category: "consumable",
    rarity: "rare",
    cost: 50,
    perk: "+50% XP for the next 2 Pomodoros",
    xpBonus: 0,
    goldBonus: 0,
    hpBonus: 0,
    lore: "An effervescent sapphire draught that sharpens concentration.",
    spriteKey: "potion_blue",
  },
  {
    id: "p_streak_shield",
    name: "Chrono-Shield Aegis",
    category: "consumable",
    rarity: "epic",
    cost: 100,
    perk: "Protects a missed habit day from breaking streak",
    xpBonus: 0,
    goldBonus: 0,
    hpBonus: 0,
    lore: "Wards your habits with a temporal bubble, granting grace when life interrupts.",
    spriteKey: "streak_shield",
  },
];

export function getItemById(id) {
  return CATALOG.find((item) => item.id === id) || null;
}

export function getItemsByCategory(category) {
  if (!category || category === "all") return CATALOG;
  return CATALOG.filter((item) => item.category === category);
}
