/**
 * jobs.js — Final Fantasy Tactics Job Classes & Ability System
 * Features 6 classic jobs: Chrono Knight, Black Mage, White Mage, Dragoon, Time Mage, Shadow Thief.
 * Full stat modifiers, AP/MP costs, AoE shapes, reaction abilities, and Limit Breaks. Zero emojis.
 */

"use strict";

export const JOBS = {
  knight: {
    id: "knight",
    name: "Chrono Knight",
    role: "Tank / Melee Striker",
    title: "Defender of Time",
    description: "Heavily armored frontliner capable of sundering enemy defenses, shielding allies, and crushing foes.",
    badgeColor: "#3b82f6",
    weaponType: "sword",
    statModifiers: {
      hp: 1.35,
      mp: 0.8,
      atk: 1.25,
      def: 1.4,
      mag: 0.7,
      spd: 0.95,
      mov: 3,
      jump: 2,
    },
    reaction: {
      id: "counter",
      name: "Counterattack",
      description: "50% chance to physically counter enemy melee strikes.",
      trigger: "damaged_melee",
    },
    limitBreak: {
      id: "omnislash",
      name: "Omnislash",
      description: "Unleashes 5 rapid-fire sword strikes on random adjacent foes, dealing massive physical damage.",
      cost: 100, // 100% Limit Gauge
      damageMultiplier: 3.5,
      aoe: "single",
      fx: "holy_burst",
    },
    abilities: [
      {
        id: "power_break",
        name: "Power Break",
        description: "Strikes enemy armor, dealing 1.2x damage and reducing target ATK by 20% for 2 turns.",
        apCost: 1,
        mpCost: 0,
        range: 1,
        aoe: "single",
        type: "physical",
        damageMultiplier: 1.2,
        debuff: { stat: "atk", amount: 0.2, duration: 2 },
      },
      {
        id: "armor_break",
        name: "Armor Break",
        description: "Shatters enemy guard, dealing 1.1x damage and reducing target DEF by 30% for 2 turns.",
        apCost: 1,
        mpCost: 0,
        range: 1,
        aoe: "single",
        type: "physical",
        damageMultiplier: 1.1,
        debuff: { stat: "def", amount: 0.3, duration: 2 },
      },
      {
        id: "shield_slam",
        name: "Shield Slam",
        description: "Barrows through target, dealing damage and pushing them back 1 tile.",
        apCost: 2,
        mpCost: 5,
        range: 1,
        aoe: "single",
        type: "physical",
        damageMultiplier: 1.4,
        knockback: 1,
      },
      {
        id: "judgment_blade",
        name: "Judgment Blade",
        description: "Holy sword burst striking target and adjacent foes with a 2-tile cross blast.",
        apCost: 2,
        mpCost: 15,
        range: 2,
        aoe: "cross",
        type: "holy",
        damageMultiplier: 1.6,
      },
    ],
  },

  black_mage: {
    id: "black_mage",
    name: "Black Mage",
    role: "Elemental Magic Nuker",
    title: "Weaver of Elements",
    description: "Master of destructive arcane magic capable of scorching cross-shaped areas with Fire, Ice, and Lightning.",
    badgeColor: "#8b5cf6",
    weaponType: "rod",
    statModifiers: {
      hp: 0.85,
      mp: 1.5,
      atk: 0.7,
      def: 0.75,
      mag: 1.5,
      spd: 1.05,
      mov: 3,
      jump: 2,
    },
    reaction: {
      id: "damage_mp",
      name: "MP Shield",
      description: "Redirects 35% of taken damage from HP to MP.",
      trigger: "damaged",
    },
    limitBreak: {
      id: "megaflare",
      name: "Megaflare",
      description: "Channels draconic astral energy to incinerate all foes in a wide 3x3 blast zone.",
      cost: 100,
      damageMultiplier: 3.8,
      aoe: "diamond_3",
      fx: "astral_fire",
    },
    abilities: [
      {
        id: "fire_cross",
        name: "Fira Blast",
        description: "Conjures scorching flames in a 5-tile cross pattern dealing Fire damage.",
        apCost: 2,
        mpCost: 12,
        range: 3,
        aoe: "cross",
        element: "fire",
        type: "magic",
        damageMultiplier: 1.5,
      },
      {
        id: "blizzard_cross",
        name: "Blizzara Shards",
        description: "Summons freezing glacial stalactites in a cross pattern with a chance to chill.",
        apCost: 2,
        mpCost: 12,
        range: 3,
        aoe: "cross",
        element: "ice",
        type: "magic",
        damageMultiplier: 1.5,
      },
      {
        id: "thundara_bolt",
        name: "Thundara Strike",
        description: "Calls down lightning on target tile with piercing shock damage.",
        apCost: 2,
        mpCost: 14,
        range: 4,
        aoe: "single",
        element: "time",
        type: "magic",
        damageMultiplier: 1.8,
      },
      {
        id: "flare",
        name: "Ancient Flare",
        description: "Unleashes concentrated non-elemental explosion penetrating 50% enemy magic defense.",
        apCost: 3,
        mpCost: 25,
        range: 3,
        aoe: "single",
        type: "magic",
        damageMultiplier: 2.4,
      },
    ],
  },

  white_mage: {
    id: "white_mage",
    name: "White Mage",
    role: "Healer & Holy Buffer",
    title: "Sanctum Cleric",
    description: "Devout protector using curative arts, protective shields (Protect/Shell), and smiting Holy light.",
    badgeColor: "#10b981",
    weaponType: "staff",
    statModifiers: {
      hp: 0.95,
      mp: 1.45,
      atk: 0.75,
      def: 0.9,
      mag: 1.35,
      spd: 1.0,
      mov: 3,
      jump: 2,
    },
    reaction: {
      id: "auto_potion",
      name: "Auto-Potion",
      description: "Automatically drinks a healing restorative when taking damage below 50% HP.",
      trigger: "damaged_critical",
    },
    limitBreak: {
      id: "divine_grace",
      name: "Divine Grace",
      description: "Restores 80% HP to all party allies and bestows Regen and Protect for 3 turns.",
      cost: 100,
      healMultiplier: 3.0,
      aoe: "all_allies",
      fx: "divine_blessing",
    },
    abilities: [
      {
        id: "cura",
        name: "Cura Restorative",
        description: "Restores vital HP to target ally or cross area of comrades.",
        apCost: 1,
        mpCost: 10,
        range: 3,
        aoe: "cross",
        type: "heal",
        healMultiplier: 1.6,
      },
      {
        id: "protect",
        name: "Protect Barrier",
        description: "Envelops an ally in glowing barrier, increasing physical DEF by 35% for 3 turns.",
        apCost: 1,
        mpCost: 8,
        range: 3,
        aoe: "single",
        type: "buff",
        buff: { stat: "def", amount: 0.35, duration: 3 },
      },
      {
        id: "shell",
        name: "Shell Aegis",
        description: "Protects target ally against magical damage, reducing spell damage taken by 40% for 3 turns.",
        apCost: 1,
        mpCost: 8,
        range: 3,
        aoe: "single",
        type: "buff",
        buff: { stat: "shell", amount: 0.4, duration: 3 },
      },
      {
        id: "holy",
        name: "Holy Pillar",
        description: "Summons a devastating column of pure sanctified radiance, smiting foes with Holy wrath.",
        apCost: 2,
        mpCost: 22,
        range: 3,
        aoe: "single",
        type: "holy",
        damageMultiplier: 2.2,
      },
    ],
  },

  dragoon: {
    id: "dragoon",
    name: "Dragoon",
    role: "Aerial Striker / Lancer",
    title: "Wyvern Knight",
    description: "Spear specialist capable of launching into the stratosphere with Jump to evade hits and deliver crushing blows.",
    badgeColor: "#0ea5e9",
    weaponType: "spear",
    statModifiers: {
      hp: 1.2,
      mp: 0.9,
      atk: 1.3,
      def: 1.15,
      mag: 0.85,
      spd: 1.1,
      mov: 4,
      jump: 4,
    },
    reaction: {
      id: "dragon_scales",
      name: "Dragon Scales",
      description: "Reduces damage from elemental magic and breath attacks by 25%.",
      trigger: "damaged_magic",
    },
    limitBreak: {
      id: "dragon_dive",
      name: "Dragon Dive",
      description: "Soars to the zenith of the sky and plunges with meteor force, dealing 3.6x damage to a 3x3 zone.",
      cost: 100,
      damageMultiplier: 3.6,
      aoe: "diamond_3",
      fx: "dragon_flame",
    },
    abilities: [
      {
        id: "jump",
        name: "Aerial Jump",
        description: "Leaps off the battlefield, evading attacks, and lands next turn dealing 2.2x piercing physical damage.",
        apCost: 2,
        mpCost: 8,
        range: 3,
        aoe: "single",
        type: "physical",
        damageMultiplier: 2.2,
      },
      {
        id: "dragon_breath",
        name: "Dragon Breath",
        description: "Exhales a 3-tile fiery line piercing straight through enemy formations.",
        apCost: 2,
        mpCost: 14,
        range: 3,
        aoe: "line",
        element: "fire",
        type: "magic",
        damageMultiplier: 1.5,
      },
      {
        id: "lancet",
        name: "Lancet Siphon",
        description: "Drives spear into target, siphoning HP and restoring 50% of damage dealt back to user.",
        apCost: 1,
        mpCost: 5,
        range: 1,
        aoe: "single",
        type: "physical",
        damageMultiplier: 1.2,
        vampiric: 0.5,
      },
    ],
  },

  time_mage: {
    id: "time_mage",
    name: "Time Mage",
    role: "Chronoturgist / Controller",
    title: "Chrono Weaver",
    description: "Alters the flow of combat time: speeding up allies with Haste, debilitating enemies with Slow/Stop, and casting Comet.",
    badgeColor: "#ec4899",
    weaponType: "staff",
    statModifiers: {
      hp: 0.9,
      mp: 1.4,
      atk: 0.75,
      def: 0.8,
      mag: 1.4,
      spd: 1.2,
      mov: 3,
      jump: 2,
    },
    reaction: {
      id: "quick",
      name: "Critical Quick",
      description: "When dropping below 30% HP, immediately gains a free extra turn.",
      trigger: "damaged_critical",
    },
    limitBreak: {
      id: "galaxy_stop",
      name: "Galaxy Stop",
      description: "Freezes time across the battlefield, inflicting Stop on all enemy units for 1 full turn.",
      cost: 100,
      aoe: "all_enemies",
      status: "stop",
      duration: 1,
      fx: "chrono_freeze",
    },
    abilities: [
      {
        id: "haste",
        name: "Haste Flow",
        description: "Accelerates target ally, granting +1 Action Point (AP) and earlier turn placement for 3 turns.",
        apCost: 1,
        mpCost: 10,
        range: 3,
        aoe: "single",
        type: "buff",
        status: "haste",
        duration: 3,
      },
      {
        id: "slow",
        name: "Slow Muddle",
        description: "Dilates time around target enemy, reducing their AP and delaying their next turn.",
        apCost: 1,
        mpCost: 10,
        range: 3,
        aoe: "single",
        type: "debuff",
        status: "slow",
        duration: 3,
      },
      {
        id: "stop",
        name: "Temporal Stop",
        description: "Halts enemy chronometry completely, rendering target unable to act for 1 turn.",
        apCost: 2,
        mpCost: 18,
        range: 3,
        aoe: "single",
        type: "debuff",
        status: "stop",
        duration: 1,
      },
      {
        id: "comet",
        name: "Comet Impact",
        description: "Summons mini astral meteor dealing high non-elemental magic damage.",
        apCost: 2,
        mpCost: 16,
        range: 3,
        aoe: "single",
        type: "magic",
        damageMultiplier: 1.7,
      },
    ],
  },

  thief: {
    id: "thief",
    name: "Shadow Thief",
    role: "High Mobility / Assassin",
    title: "Nightblade Scout",
    description: "Acrobatic shadow striker with unmatched mobility (MOV 5), dual strike capabilities, and item/gold thievery.",
    badgeColor: "#f59e0b",
    weaponType: "dagger",
    statModifiers: {
      hp: 1.05,
      mp: 0.9,
      atk: 1.2,
      def: 0.95,
      mag: 0.85,
      spd: 1.4,
      mov: 5,
      jump: 3,
    },
    reaction: {
      id: "evade",
      name: "Shadow Step",
      description: "25% base chance to completely evade physical attacks.",
      trigger: "attacked",
    },
    limitBreak: {
      id: "shadow_mirage",
      name: "Shadow Mirage",
      description: "Creates shadow clones that strike all surrounding foes and grants absolute Vanish/Invisibility for 2 turns.",
      cost: 100,
      damageMultiplier: 3.2,
      aoe: "cross",
      buff: { status: "vanish", duration: 2 },
      fx: "shadow_smoke",
    },
    abilities: [
      {
        id: "dual_strike",
        name: "Twin Fang Strike",
        description: "Quick flurry of two rapid dagger strikes with high critical hit probability.",
        apCost: 1,
        mpCost: 6,
        range: 1,
        aoe: "single",
        type: "physical",
        damageMultiplier: 1.4,
        critBonus: 0.3,
      },
      {
        id: "steal_gil",
        name: "Pickpocket",
        description: "Attacks target and steals 15-35 Gold coins on hit.",
        apCost: 1,
        mpCost: 4,
        range: 1,
        aoe: "single",
        type: "physical",
        damageMultiplier: 0.9,
        stealGold: true,
      },
      {
        id: "shadowstitch",
        name: "Shadowstitch",
        description: "Pins target's shadow to the floor, dealing damage and immobilizing them (0 MOV) for 2 turns.",
        apCost: 2,
        mpCost: 12,
        range: 2,
        aoe: "single",
        type: "physical",
        damageMultiplier: 1.2,
        status: "immobilize",
        duration: 2,
      },
    ],
  },
};

export function getJob(jobId) {
  return JOBS[jobId] || JOBS.knight;
}

export function getAllJobs() {
  return Object.values(JOBS);
}
