/**
 * profileCatalog.js — Multi-Tenant Personas & Pre-Populated Dataset Catalog
 * Defines realistic, rich user personas with complete initial workspaces,
 * habit routines, markdown vault documents, RPG heroes, and privacy sharing permissions.
 * Zero emojis — 100% SVG icons & semantic metadata.
 */

"use strict";

export const TENANT_PERSONAS = {
  tenant_novice: {
    id: "tenant_novice",
    name: "You",
    handle: "@apprentice",
    title: "Focus Apprentice & New Adventurer",
    role: "user",
    accent: "#10b981",
    avatarMascot: "pomi",
    bio: "Embarking on a focus quest. Mastering the Pomodoro technique, building daily streaks, and discovering companions.",
    status: "Starting my focus journey with Pomi",
    level: 1,
    className: "Novice",
    streak: 0,
    focusHours: 0,
    room: "Indie Ship Room",
    privacySettings: {
      shareStreak: true,
      shareCurrentTask: true,
      shareVaultNotes: false,
      shareFocusRoom: true,
      allowNudges: true,
    },
    hero: {
      archetype: "adventurer",
      name: "You",
      level: 1,
      xp: 0,
      maxXp: 100,
      hp: 100,
      maxHp: 100,
      gold: 80,
      equipped: {
        weapon: { id: "w_training_staff", name: "Wooden Focus Wand", category: "weapon" },
        armor: { id: "a_apprentice_tunic", name: "Linen Practice Robes", category: "armor", hpBonus: 5 },
        headgear: { id: "h_none", name: "None", category: "headgear" },
        cloak: { id: "c_none", name: "None", category: "cloak" },
        offhand: { id: "o_none", name: "None", category: "offhand" },
        mount: { id: "m_none", name: "None", category: "mount" },
      },
      inventory: ["w_training_staff", "a_apprentice_tunic"],
    },
    tasks: [
      { id: "nov_1", name: "Complete the 5-step companion interactive tutorial", priority: "high", dueDate: "Today", completed: false },
      { id: "nov_2", name: "Start your first 25-minute Pomodoro focus sprint", priority: "high", dueDate: "Today", completed: false },
      { id: "nov_3", name: "Visit Accountability Lounge & send a High-Five to squad", priority: "medium", dueDate: "Tomorrow", completed: false },
      { id: "nov_4", name: "Equip your starter wand in the Hero Bazaar", priority: "medium", dueDate: "", completed: false },
      { id: "nov_5", name: "Help a companion solve a chore in the Workshop", priority: "low", dueDate: "", completed: false },
    ],
    habits: [
      { id: "hab_nov_1", name: "Drink 1 glass of water after each focus block", category: "health", frequency: "daily", streak: 0, history: {} },
      { id: "hab_nov_2", name: "Review daily priorities before timer start", category: "focus", frequency: "daily", streak: 0, history: {} },
    ],
    vaultNotes: [
      { id: "vn_nov_1", title: "Welcome to Pomidor Vault", tags: ["guide", "getting-started"], content: "# Welcome to Pomidor\n\nYour personal focus workspace is ready.\n\n- Press Space or Play to start a 25-minute focus sprint.\n- Use Markdown in the Vault to capture notes during breaks.\n- Level up your companion and hero through daily consistency.\n- Join focus chambers in the Accountability Lounge to work alongside peers." },
    ],
    stats: {
      totalPomodoros: 0,
      totalFocusMinutes: 0,
      currentStreak: 0,
      longestStreak: 0,
    },
  },

  tenant_admin: {
    id: "tenant_admin",
    name: "Shug",
    handle: "@chrono_architect",
    title: "System Architect & Super Admin",
    role: "admin",
    accent: "#ef4444",
    avatarMascot: "chronos",
    bio: "Chief architect of the Chrono Productivity System. Overseeing system telemetry, bot deterrence, and temporal stability.",
    status: "Administering Temporal Continuum & Reviewing Telemetry",
    level: 25,
    className: "Grand Chronomancer",
    streak: 45,
    focusHours: 420,
    room: "Temporal Control Vault",
    privacySettings: {
      shareStreak: true,
      shareCurrentTask: true,
      shareVaultNotes: true,
      shareFocusRoom: true,
      allowNudges: true,
    },
    hero: {
      archetype: "mage",
      name: "Shug",
      level: 25,
      xp: 1250,
      maxXp: 3000,
      hp: 240,
      maxHp: 240,
      gold: 1450,
      equipped: {
        weapon: { id: "w_staff_aeons", name: "Staff of Aeons", category: "weapon" },
        armor: { id: "a_royal_plate", name: "Royal Chrono Robes", category: "armor", hpBonus: 40 },
        headgear: { id: "h_scholar_circlet", name: "Circlet of the Timeless", category: "headgear" },
        cloak: { id: "c_shadow_cloak", name: "Aegis Mantle", category: "cloak" },
        offhand: { id: "o_chrono_sigil", name: "Chrono Sovereign Sigil", category: "offhand", hpBonus: 50 },
        mount: { id: "m_solar_hare", name: "Aether Owl", category: "mount" },
      },
      inventory: ["w_staff_aeons", "a_royal_plate", "h_scholar_circlet", "c_shadow_cloak", "o_chrono_sigil", "m_solar_hare"],
    },
    tasks: [
      { id: "adm_1", name: "Review GA4 production telemetry event ingestion", priority: "high", dueDate: "Today", completed: true },
      { id: "adm_2", name: "Audit bot deterrence heuristics and cursor entropy thresholds", priority: "high", dueDate: "Today", completed: false },
      { id: "adm_3", name: "Verify multi-tenant isolation and tenant snapshot migrations", priority: "medium", dueDate: "Tomorrow", completed: false },
      { id: "adm_4", name: "Deploy updated zero-emoji SVG icon registry", priority: "low", dueDate: "", completed: true },
      { id: "adm_5", name: "Benchmark client storage footprint across active partitions", priority: "medium", dueDate: "Friday", completed: false },
    ],
    habits: [
      { id: "hab_adm_1", name: "Morning telemetry & exception audit", category: "work", frequency: "daily", streak: 45, history: { [new Date().toISOString().split("T")[0]]: true } },
      { id: "hab_adm_2", name: "Daily 90m deep focus sprint", category: "focus", frequency: "daily", streak: 30, history: { [new Date().toISOString().split("T")[0]]: true } },
      { id: "hab_adm_3", name: "Weekly partition state backup", category: "work", frequency: "weekly", streak: 12, history: { [new Date().toISOString().split("T")[0]]: true } },
    ],
    vaultNotes: [
      { id: "vn_adm_1", title: "System Architecture Specification v3.0", tags: ["architecture", "telemetry"], content: "# Chrono Workspace Architecture\n\n- Client-Side Multi-Tenant isolation with hot-swappable storage slots.\n- GA4 custom dimensions pipeline with automatic offline buffer.\n- Real-time interaction density heatmaps on full-viewport canvas." },
      { id: "vn_adm_2", title: "Bot Classification Matrix", tags: ["security", "heuristics"], content: "# Heuristic Differentiation\n\nScores >= 60 flag automation drivers (WebDriver, headless Chrome, linear mouse vectors)." },
    ],
    stats: {
      totalPomodoros: 840,
      totalFocusMinutes: 25200,
      currentStreak: 45,
      longestStreak: 45,
    },
  },

  tenant_elena: {
    id: "tenant_elena",
    name: "Elena Rostova",
    handle: "@elena_rust",
    title: "Staff Distributed Systems Engineer",
    role: "user",
    accent: "#06b6d4",
    avatarMascot: "kip",
    bio: "Building fault-tolerant consensus protocols in Rust. Kip enthusiast. Relentless refactorer of messy state machines.",
    status: "Benchmarking Raft Consensus Heartbeats in Rust",
    level: 14,
    className: "Chrono Knight",
    streak: 18,
    focusHours: 185,
    room: "Deep Code Chamber",
    privacySettings: {
      shareStreak: true,
      shareCurrentTask: true,
      shareVaultNotes: false,
      shareFocusRoom: true,
      allowNudges: true,
    },
    hero: {
      archetype: "knight",
      name: "Elena",
      level: 14,
      xp: 420,
      maxXp: 950,
      hp: 175,
      maxHp: 175,
      gold: 380,
      equipped: {
        weapon: { id: "w_runic_blade", name: "Runic Compiler Blade", category: "weapon" },
        armor: { id: "a_knight_cuirass", name: "Zero-Cost Steel Armor", category: "armor", hpBonus: 25 },
        headgear: { id: "h_focus_band", name: "Band of Deep Flow", category: "headgear" },
        cloak: { id: "c_none", name: "None", category: "cloak" },
        offhand: { id: "o_aegis_shield", name: "Memory Safety Aegis", category: "offhand", hpBonus: 20 },
        mount: { id: "m_none", name: "None", category: "mount" },
      },
      inventory: ["w_runic_blade", "a_knight_cuirass", "h_focus_band", "o_aegis_shield"],
    },
    tasks: [
      { id: "ele_1", name: "Implement split-vote randomized election timeout in Raft", priority: "high", dueDate: "Today", completed: true },
      { id: "ele_2", name: "Fix async channel backpressure deadlocks under high load", priority: "high", dueDate: "Today", completed: false },
      { id: "ele_3", name: "Benchmark log compaction using memory-mapped SSTables", priority: "medium", dueDate: "Tomorrow", completed: false },
      { id: "ele_4", name: "Tune crossbeam thread pool steal queue latency", priority: "medium", dueDate: "Thursday", completed: false },
      { id: "ele_5", name: "Write property-based fuzz tests for log serialization", priority: "low", dueDate: "", completed: true },
    ],
    habits: [
      { id: "hab_ele_1", name: "Morning code review sprint (30m)", category: "work", frequency: "daily", streak: 18, history: { [new Date().toISOString().split("T")[0]]: true } },
      { id: "hab_ele_2", name: "Hydration break between compile runs", category: "health", frequency: "daily", streak: 12, history: { [new Date().toISOString().split("T")[0]]: true } },
      { id: "hab_ele_3", name: "Post-standup architecture journaling", category: "focus", frequency: "daily", streak: 15, history: { [new Date().toISOString().split("T")[0]]: true } },
    ],
    vaultNotes: [
      { id: "vn_ele_1", title: "Raft Log Compaction Strategy", tags: ["rust", "distributed-systems"], content: "# Raft Log Compaction\n\nSnapshots take time. Implement incremental background checkpointing with WAL replay safety." },
      { id: "vn_ele_2", title: "Tokio Runtime Concurrency Patterns", tags: ["rust", "tokio"], content: "# Tokio Work Stealing\n\nAvoid blocking compute tasks on core I/O threads; spawn_blocking for disk writes." },
    ],
    stats: {
      totalPomodoros: 370,
      totalFocusMinutes: 11100,
      currentStreak: 18,
      longestStreak: 24,
    },
  },

  tenant_darius: {
    id: "tenant_darius",
    name: "Dr. Darius Vance",
    handle: "@dr_vance",
    title: "Neuroscience Resident & Clinical Researcher",
    role: "user",
    accent: "#eab308",
    avatarMascot: "bolt",
    bio: "Navigating residency shifts and neuroanatomy board review. Using Clockwork Bot Bolt to audit study hours with mechanical precision.",
    status: "Spaced Repetition: Cranial Nerves VII & IX Pathways",
    level: 9,
    className: "Clockwork Scholar",
    streak: 32,
    focusHours: 310,
    room: "Silent Medical Library",
    privacySettings: {
      shareStreak: true,
      shareCurrentTask: true,
      shareVaultNotes: false,
      shareFocusRoom: true,
      allowNudges: true,
    },
    hero: {
      archetype: "mage",
      name: "Darius",
      level: 9,
      xp: 210,
      maxXp: 620,
      hp: 130,
      maxHp: 130,
      gold: 240,
      equipped: {
        weapon: { id: "w_staff_aeons", name: "Neural Probe Staff", category: "weapon" },
        armor: { id: "a_apprentice_tunic", name: "Clinical White Lab Coat", category: "armor", hpBonus: 15 },
        headgear: { id: "h_scholar_circlet", name: "Circlet of Synapses", category: "headgear" },
        cloak: { id: "c_none", name: "None", category: "cloak" },
        offhand: { id: "o_none", name: "None", category: "offhand" },
        mount: { id: "m_none", name: "None", category: "mount" },
      },
      inventory: ["w_staff_aeons", "a_apprentice_tunic", "h_scholar_circlet"],
    },
    tasks: [
      { id: "dar_1", name: "Complete 200 Anki flashcards on Brainstem Strokes", priority: "high", dueDate: "Today", completed: true },
      { id: "dar_2", name: "Review MRI angiography slides for clinical grand rounds", priority: "high", dueDate: "Today", completed: false },
      { id: "dar_3", name: "Draft methodology section for Parkinson's tremor study", priority: "medium", dueDate: "Friday", completed: false },
      { id: "dar_4", name: "Update neuro-ICU patient handoff summary documentation", priority: "high", dueDate: "Today", completed: true },
      { id: "dar_5", name: "Annotate clinical paper on DBS target localization", priority: "low", dueDate: "Sunday", completed: false },
    ],
    habits: [
      { id: "hab_dar_1", name: "Daily 50 Anki cards before ward rounds", category: "study", frequency: "daily", streak: 32, history: { [new Date().toISOString().split("T")[0]]: true } },
      { id: "hab_dar_2", name: "Evening mindfulness breathing (Pip pacer)", category: "health", frequency: "daily", streak: 20, history: { [new Date().toISOString().split("T")[0]]: true } },
      { id: "hab_dar_3", name: "Daily medical journal reading (20m)", category: "study", frequency: "daily", streak: 14, history: { [new Date().toISOString().split("T")[0]]: true } },
    ],
    vaultNotes: [
      { id: "vn_dar_1", title: "Cranial Nerves Differential Guide", tags: ["medicine", "neuro"], content: "# Cranial Nerves Summary\n\nCN VII vs CN IX testing procedures and pontine lesion localization." },
      { id: "vn_dar_2", title: "Stroke Code Protocol Cheat Sheet", tags: ["clinical", "emergency"], content: "# tPA & Thrombectomy Criteria\n\nNIHSS assessment thresholds and CT perfusion mismatch criteria." },
    ],
    stats: {
      totalPomodoros: 620,
      totalFocusMinutes: 18600,
      currentStreak: 32,
      longestStreak: 32,
    },
  },

  tenant_aiko: {
    id: "tenant_aiko",
    name: "Aiko Tanaka",
    handle: "@aiko_ui",
    title: "Design Systems Lead & Interface Specialist",
    role: "user",
    accent: "#3b82f6",
    avatarMascot: "pip",
    bio: "Obsessed with accessible color contrast, micro-interactions, and double-bezel containers. Calmed by Pip and cold brew.",
    status: "Auditing WCAG 2.2 AA Contrast & Token Hierarchy",
    level: 11,
    className: "Zen Navigator",
    streak: 14,
    focusHours: 140,
    room: "Design Sprint Lab",
    privacySettings: {
      shareStreak: true,
      shareCurrentTask: true,
      shareVaultNotes: true,
      shareFocusRoom: true,
      allowNudges: true,
    },
    hero: {
      archetype: "paladin",
      name: "Aiko",
      level: 11,
      xp: 310,
      maxXp: 740,
      hp: 155,
      maxHp: 155,
      gold: 510,
      equipped: {
        weapon: { id: "w_sun_halberd", name: "Stylus of Precision", category: "weapon" },
        armor: { id: "a_padded_leather", name: "Ergonomic Studio Garb", category: "armor", hpBonus: 20 },
        headgear: { id: "h_focus_band", name: "Headband of Alignment", category: "headgear" },
        cloak: { id: "c_none", name: "None", category: "cloak" },
        offhand: { id: "o_none", name: "None", category: "offhand" },
        mount: { id: "m_none", name: "None", category: "mount" },
      },
      inventory: ["w_sun_halberd", "a_padded_leather", "h_focus_band"],
    },
    tasks: [
      { id: "aik_1", name: "Publish tokens/semantic-colors.json update to npm", priority: "high", dueDate: "Today", completed: true },
      { id: "aik_2", name: "Review PR #412: Button-in-button trailing icon spring physics", priority: "high", dueDate: "Today", completed: false },
      { id: "aik_3", name: "Create interactive Figma prototypes for Heatmap HUD", priority: "medium", dueDate: "Tomorrow", completed: false },
      { id: "aik_4", name: "Audit color tokens for OLED dark mode contrast ratios", priority: "medium", dueDate: "Thursday", completed: false },
      { id: "aik_5", name: "Design vector SVG badges for Accountability Lounge", priority: "low", dueDate: "", completed: true },
    ],
    habits: [
      { id: "hab_aik_1", name: "Daily design audit sprint (45m)", category: "work", frequency: "daily", streak: 14, history: { [new Date().toISOString().split("T")[0]]: true } },
      { id: "hab_aik_2", name: "Post-standup ergonomic stretch", category: "health", frequency: "daily", streak: 9, history: { [new Date().toISOString().split("T")[0]]: true } },
      { id: "hab_aik_3", name: "Sketch 1 new interaction concept daily", category: "creative", frequency: "daily", streak: 7, history: { [new Date().toISOString().split("T")[0]]: true } },
    ],
    vaultNotes: [
      { id: "vn_aik_1", title: "Double-Bezel Design Tokens Spec", tags: ["design-system", "tokens"], content: "# Double-Bezel System\n\nConcentric corner radii: R_outer = R_inner + padding. Maintain 1px border stroke with inset subtle shadow." },
      { id: "vn_aik_2", title: "Micro-Interaction Motion Curves", tags: ["animation", "css"], content: "# Spring Timing Curves\n\nFast snap: cubic-bezier(0.16, 1, 0.3, 1). Hover elevation: 150ms ease-out." },
    ],
    stats: {
      totalPomodoros: 280,
      totalFocusMinutes: 8400,
      currentStreak: 14,
      longestStreak: 21,
    },
  },

  tenant_leo: {
    id: "tenant_leo",
    name: "Leo Morales",
    handle: "@leo_builds",
    title: "Indie Founder & Solo Operator",
    role: "user",
    accent: "#10b981",
    avatarMascot: "pomi",
    bio: "Shipping products in public. Fighting procrastination with Pomi. Doing sales, frontend, backend, and support in 25-minute sprints.",
    status: "Iterating v2 Landing Page Value Prop & Stripe Checkout",
    level: 7,
    className: "Solar Paladin",
    streak: 7,
    focusHours: 95,
    room: "Indie Ship Room",
    privacySettings: {
      shareStreak: true,
      shareCurrentTask: true,
      shareVaultNotes: false,
      shareFocusRoom: true,
      allowNudges: true,
    },
    hero: {
      archetype: "rogue",
      name: "Leo",
      level: 7,
      xp: 150,
      maxXp: 480,
      hp: 110,
      maxHp: 110,
      gold: 195,
      equipped: {
        weapon: { id: "w_dual_daggers", name: "Ship-Fast Twin Daggers", category: "weapon" },
        armor: { id: "a_padded_leather", name: "Coffee-Proof Hoodie", category: "armor", hpBonus: 10 },
        headgear: { id: "h_focus_band", name: "Hacker Beanie", category: "headgear" },
        cloak: { id: "c_none", name: "None", category: "cloak" },
        offhand: { id: "o_none", name: "None", category: "offhand" },
        mount: { id: "m_none", name: "None", category: "mount" },
      },
      inventory: ["w_dual_daggers", "a_padded_leather", "h_focus_band"],
    },
    tasks: [
      { id: "leo_1", name: "Hook up Stripe webhook handler for customer subscription created", priority: "high", dueDate: "Today", completed: true },
      { id: "leo_2", name: "Email 10 beta users who churned during onboarding", priority: "high", dueDate: "Today", completed: false },
      { id: "leo_3", name: "Publish build-in-public weekly revenue report", priority: "medium", dueDate: "Thursday", completed: false },
      { id: "leo_4", name: "Set up PostHog funnel for checkout step dropoff", priority: "medium", dueDate: "Friday", completed: false },
      { id: "leo_5", name: "Prepare Product Hunt launch day maker comment draft", priority: "low", dueDate: "", completed: true },
    ],
    habits: [
      { id: "hab_leo_1", name: "1 Pomodoro of customer outreach daily", category: "growth", frequency: "daily", streak: 7, history: { [new Date().toISOString().split("T")[0]]: true } },
      { id: "hab_leo_2", name: "Zero inbox sprint before lunch", category: "work", frequency: "daily", streak: 5, history: { [new Date().toISOString().split("T")[0]]: true } },
      { id: "hab_leo_3", name: "Evening revenue and churn review", category: "finance", frequency: "daily", streak: 6, history: { [new Date().toISOString().split("T")[0]]: true } },
    ],
    vaultNotes: [
      { id: "vn_leo_1", title: "Conversion Optimization Brainstorm", tags: ["marketing", "growth"], content: "# Conversion Ideas\n\nHero section needs clearer trust badges and an interactive tour CTA.\nEnsure 1-click checkout without extra signup friction." },
      { id: "vn_leo_2", title: "Product Hunt Launch Playbook", tags: ["launch", "playbook"], content: "# Launch Day Timetable\n\n12:01 AM PST launch. Respond to comments in real-time. Post on Twitter and LinkedIn." },
    ],
    stats: {
      totalPomodoros: 190,
      totalFocusMinutes: 5700,
      currentStreak: 7,
      longestStreak: 12,
    },
  },
};
